package com.next.db.mapper;

import com.next.db.model.FunOrderItem;
import com.next.db.model.FunOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int countByExample(FunOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int deleteByExample(FunOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int insert(FunOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int insertSelective(FunOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    List<FunOrderItem> selectByExample(FunOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    FunOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") FunOrderItem record, @Param("example") FunOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByExample(@Param("record") FunOrderItem record, @Param("example") FunOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByPrimaryKeySelective(FunOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorderitem
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByPrimaryKey(FunOrderItem record);
}