package com.next.db.mapper;

import com.next.db.model.FunOrder;
import com.next.db.model.FunOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int countByExample(FunOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int deleteByExample(FunOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int insert(FunOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int insertSelective(FunOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    List<FunOrder> selectByExample(FunOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    FunOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") FunOrder record, @Param("example") FunOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByExample(@Param("record") FunOrder record, @Param("example") FunOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByPrimaryKeySelective(FunOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funorder
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    int updateByPrimaryKey(FunOrder record);
}