package com.next.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class FunOrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.id
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.funorderId
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private Integer funorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.productName
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.quantity
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.price
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.productType
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.createdBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.createdDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.lastModifiedBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private String lastModifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funorderitem.lastModifiedDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.id
     *
     * @return the value of funorderitem.id
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.id
     *
     * @param id the value for funorderitem.id
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.funorderId
     *
     * @return the value of funorderitem.funorderId
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public Integer getFunorderId() {
        return funorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.funorderId
     *
     * @param funorderId the value for funorderitem.funorderId
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setFunorderId(Integer funorderId) {
        this.funorderId = funorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.productName
     *
     * @return the value of funorderitem.productName
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.productName
     *
     * @param productName the value for funorderitem.productName
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.quantity
     *
     * @return the value of funorderitem.quantity
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.quantity
     *
     * @param quantity the value for funorderitem.quantity
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.price
     *
     * @return the value of funorderitem.price
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.price
     *
     * @param price the value for funorderitem.price
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.productType
     *
     * @return the value of funorderitem.productType
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.productType
     *
     * @param productType the value for funorderitem.productType
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.createdBy
     *
     * @return the value of funorderitem.createdBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.createdBy
     *
     * @param createdBy the value for funorderitem.createdBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.createdDate
     *
     * @return the value of funorderitem.createdDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.createdDate
     *
     * @param createdDate the value for funorderitem.createdDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.lastModifiedBy
     *
     * @return the value of funorderitem.lastModifiedBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.lastModifiedBy
     *
     * @param lastModifiedBy the value for funorderitem.lastModifiedBy
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funorderitem.lastModifiedDate
     *
     * @return the value of funorderitem.lastModifiedDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funorderitem.lastModifiedDate
     *
     * @param lastModifiedDate the value for funorderitem.lastModifiedDate
     *
     * @mbggenerated Sat Mar 03 21:49:17 CST 2018
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}