package com.next.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class FunProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.id
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.productName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.img
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.shopName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.sku
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.path
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.pirce
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private BigDecimal pirce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.createdBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.createdDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.lastModifiedBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private String lastModifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funproduct.lastModifiedDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.id
     *
     * @return the value of funproduct.id
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.id
     *
     * @param id the value for funproduct.id
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.productName
     *
     * @return the value of funproduct.productName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.productName
     *
     * @param productName the value for funproduct.productName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.img
     *
     * @return the value of funproduct.img
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.img
     *
     * @param img the value for funproduct.img
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.shopName
     *
     * @return the value of funproduct.shopName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.shopName
     *
     * @param shopName the value for funproduct.shopName
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.sku
     *
     * @return the value of funproduct.sku
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.sku
     *
     * @param sku the value for funproduct.sku
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.path
     *
     * @return the value of funproduct.path
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.path
     *
     * @param path the value for funproduct.path
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.pirce
     *
     * @return the value of funproduct.pirce
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public BigDecimal getPirce() {
        return pirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.pirce
     *
     * @param pirce the value for funproduct.pirce
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setPirce(BigDecimal pirce) {
        this.pirce = pirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.createdBy
     *
     * @return the value of funproduct.createdBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.createdBy
     *
     * @param createdBy the value for funproduct.createdBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.createdDate
     *
     * @return the value of funproduct.createdDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.createdDate
     *
     * @param createdDate the value for funproduct.createdDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.lastModifiedBy
     *
     * @return the value of funproduct.lastModifiedBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.lastModifiedBy
     *
     * @param lastModifiedBy the value for funproduct.lastModifiedBy
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funproduct.lastModifiedDate
     *
     * @return the value of funproduct.lastModifiedDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funproduct.lastModifiedDate
     *
     * @param lastModifiedDate the value for funproduct.lastModifiedDate
     *
     * @mbggenerated Sun Mar 04 17:09:19 CST 2018
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}